<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function categories() {
        return $this->belongsToMany(Category::class);
    }

    public function getRouteKeyName() {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}
