<?php

namespace App;

use App\User;
use App\Country;
use App\State;
use App\City;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Profile extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
    protected $appends = ['address'];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function user()
    {
        return $this->belongsTo('App\User')
            ->select(['id', 'email', 'role_id', 'status']);
    }

    public function getUserRoles() {
        return $this->user->role ?  $this->user->role->id : null;
    }

    public function country()
    {
        return $this->belongsTo('App\Country');
    }

    public function state()
    {
        return $this->belongsTo('App\State');
    }

    public function city()
    {
        return $this->belongsTo('App\City');
    }


    public function getAddressAttribute() {
        return "{$this->country->name} {$this->state->name} {$this->city->name}";
    }

}
